name: Delete Old Commits

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/.delete-old-commits.yml

jobs:
  delete_old_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install git-filter-repo
        run: |
          pip install git-filter-repo

      - name: Delete old commits
        run: |
          # Get the timestamp of the latest commit
          LATEST_COMMIT_TIMESTAMP=$(git log -1 --format=%ct)
          
          # Calculate the timestamp for one day ago
          ONE_DAY_AGO=$((LATEST_COMMIT_TIMESTAMP - 86400))
          
          # Use git-filter-repo to keep only commits from the last day
          git-filter-repo --force --invert-paths --path-match . --before $ONE_DAY_AGO

      - name: Dry run - Print git log
        if: github.event_name != 'schedule'
        run: |
          git log --oneline

      - name: Force push changes
        if: github.event_name == 'schedule'
        run: |
          git push origin --force --all

