name: Dump PATH Environment Variable

on:
  push:
    paths:
      - .github/workflows/crossplatform.yml
  workflow_dispatch:

jobs:
  dump-path:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest  # Arm
          - macos-13      # Intel
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Dump PATH
        run: |
          echo "PATH environment variable:"
          echo "$PATH" | xargs -d: -n1
        shell: bash
