name: Dump PATH

on:
  push:
    paths:
      - .github/workflows/Dump-PATH.yml
  workflow_dispatch:

jobs:
  'dump-path':
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest  # Arm
          - macos-13      # Intel
    runs-on: ${{ matrix.os }}
    steps:
      - name: Dump PATH
        run: |
          echo "PATH environment variable:"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          printf "%s\n" "${PATH}" | tr ':' '\n' | tee -a "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
        shell: bash
