name: Dump PATH Environment Variable

on:
  push:
    paths:
      - .github/workflows/Dump-PATH.yml
  workflow_dispatch:

jobs:
  'dump-path':
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest  # Arm
          - macos-13      # Intel
    runs-on: ${{ matrix.os }}
    steps:
      - name: Dump PATH
        run: |
          echo "PATH environment variable:"
          printf "%s\n" "${PATH}" | tr ':' '\n' | xargs -n1
        shell: bash
