name: "Previous Step Referencing Demo"

on:
  workflow_dispatch:

jobs:
  'demo':
    runs-on: 'ubuntu-latest'

    steps:
      - name: "Step #0"
        id: step0
        run: echo "value=STEP_0" >> $GITHUB_OUTPUT

      - name: "Step #1"
        id: step1
        run: echo "value=STEP_1" >> $GITHUB_OUTPUT

      - name: "Step #2"
        id: step2
        run: echo "value=STEP_2" >> $GITHUB_OUTPUT

      - name: Use the output from the previous step
        # run: echo "The output from the previous step is: "
        run: |
          echo "${STEPS}" | jq -C .
        env:
          STEPS: ${{ toJSON(steps) }}
