name: "Previous Step Referencing Demo"

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/Prev-Step-Ref-Demo.yml"
  workflow_dispatch:

jobs:
  'demo':
    runs-on: 'ubuntu-latest'

    steps:
      - name: "Step #0"
        id: 'step0'
        run: |
          echo "output1=STEP_0_VALUE1" >> $GITHUB_OUTPUT
          echo "output2=STEP_0_VALUE2" >> $GITHUB_OUTPUT
          echo "output3=STEP_0_VALUE3" >> $GITHUB_OUTPUT

      - name: "Step #1"
        id: 'step1'
        run: |
          echo "output1=STEP_1_VALUE1" >> $GITHUB_OUTPUT
          echo "output2=STEP_1_VALUE2" >> $GITHUB_OUTPUT
          echo "output3=STEP_1_VALUE3" >> $GITHUB_OUTPUT

      - name: "Step #2"
        id: 'step2'
        run: |
          echo "output1=STEP_2_VALUE1" >> $GITHUB_OUTPUT
          echo "output2=STEP_2_VALUE2" >> $GITHUB_OUTPUT
          echo "output3=STEP_2_VALUE3" >> $GITHUB_OUTPUT

      - name: "Use the output from the previous step"
        uses: 'actions/github-script@main'
        with:
          script: |
            const steps = JSON.parse(process.env['STEPS'])
            const prevStep = steps[Object.keys(steps).pop()]

            console.log(prevStep)
            // {
            //   "outputs": {
            //     "output1": "STEP_2_VALUE1",
            //     "output2": "STEP_2_VALUE2",
            //     "output3": "STEP_2_VALUE3"
            //   },
            //   "outcome": "success",
            //   "conclusion": "success"
            // }

            core.summary.addHeading('Previous step', '2')
            core.summary.addCodeBlock(JSON.stringify(prevStep, null, "  "), 'json')
            core.summary.write()
        env:
          'STEPS': ${{ toJSON(steps) }}


      - name: "Filter only outputs"
        uses: 'actions/github-script@main'
        with:
          script: |
            const outputs = JSON.parse(process.env['OUTPUTS'])
            const prevStepOutputs = outputs[Object.keys(outputs).pop()]

            console.log(prevStepOutputs)
            // {
            //   "output1": "STEP_2_VALUE1",
            //   "output2": "STEP_2_VALUE2",
            //   "output3": "STEP_2_VALUE3"
            // }

            core.summary.addHeading('Previous step outputs', '2')
            core.summary.addCodeBlock(JSON.stringify(prevStepOutputs, null, "  "), 'json')
            core.summary.write()
        env:
          'OUTPUTS': ${{ toJSON(steps.*.outputs) }}
